/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface IYourContract {
    function setGreeting(string calldata new_greeting) external payable;

    function withdraw() external;

    function greeting() external view returns (string memory);

    function owner() external view returns (address);

    function premium() external view returns (bool);

    function totalCounter() external view returns (uint256);

    function userGreetingCounter(address _user) external view returns (uint256);

    error NotOwnerError();
}
